language: cpp
os:
  - linux
  - osx
dist: trusty
addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - mingw-w64
install: true
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make linux_release; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make windows_release; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then make macos_release; fi
