language: cpp
os:
  - linux
  - osx
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - mingw-w64
install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://www.libsdl.org/release/SDL2-devel-2.0.5-mingw.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xf SDL2-devel-2.0.5-mingw.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo cp -r SDL2-2.0.5/i686-w64-mingw32/include/* /usr/i686-w64-mingw32/include; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo cp -r SDL2-2.0.5/i686-w64-mingw32/lib/* /usr/i686-w64-mingw32/lib; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-devel-2.0.1-mingw.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xf SDL2_mixer-devel-2.0.1-mingw.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo cp -r SDL2_mixer-2.0.1/i686-w64-mingw32/include/* /usr/i686-w64-mingw32/include; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo cp -r SDL2_mixer-2.0.1/i686-w64-mingw32/lib/* /usr/i686-w64-mingw32/lib; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-devel-2.0.14-mingw.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then tar -xf SDL2_ttf-devel-2.0.14-mingw.tar.gz; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo cp -r SDL2_ttf-2.0.14/i686-w64-mingw32/include/* /usr/i686-w64-mingw32/include; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo cp -r SDL2_ttf-2.0.14/i686-w64-mingw32/lib/* /usr/i686-w64-mingw32/lib; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget https://www.libsdl.org/release/SDL2-2.0.5.dmg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then hdiutil attach SDL2-2.0.5.dmg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo cp -r /Volumes/SDL2/SDL2.framework /Library/Frameworks; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget https://www.libsdl.org/projects/SDL_mixer/release/SDL2_mixer-2.0.1.dmg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then hdiutil attach SDL2_mixer-2.0.1.dmg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo cp -r /Volumes/SDL2_mixer/SDL2_mixer.framework /Library/Frameworks; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then wget https://www.libsdl.org/projects/SDL_ttf/release/SDL2_ttf-2.0.14.dmg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then hdiutil attach SDL2_ttf-2.0.14.dmg; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then sudo cp -r /Volumes/SDL2_ttf/SDL2_ttf.framework /Library/Frameworks; fi
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make linux; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make windows; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then make macos; fi
