language: cpp
os:
  - linux
  - osx
dist: trusty
sudo: required
addons:
  apt:
    packages:
      - libsdl2-dev
      - libsdl2-mixer-dev
      - libsdl2-ttf-dev
      - mingw-w64
install: true
script:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make linux; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then make windows; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then make macos; fi
