/** @file TextureManager.hpp
 * Load and provide to other subsystems all game textures.
 * @author Adrien RICCIARDI
 */
#ifndef HPP_TEXTURE_MANAGER_HPP
#define HPP_TEXTURE_MANAGER_HPP

#include <Texture.hpp>

namespace TextureManager
{

/** All available textures. */
typedef enum
{
	// Scene floors
	TEXTURE_ID_SCENE_FLOOR_0,
	TEXTURE_ID_SCENE_FLOOR_1,
	TEXTURE_ID_SCENE_FLOOR_2,
	TEXTURE_ID_SCENE_FLOOR_3,
	TEXTURE_ID_SCENE_FLOOR_4,
	TEXTURE_ID_SCENE_FLOOR_5,
	TEXTURE_ID_SCENE_FLOOR_6,
	TEXTURE_ID_SCENE_FLOOR_7,
	TEXTURE_ID_SCENE_FLOOR_8,
	TEXTURE_ID_SCENE_FLOOR_9,
	TEXTURE_ID_SCENE_FLOOR_10,
	TEXTURE_ID_SCENE_FLOOR_11,
	TEXTURE_ID_SCENE_FLOOR_12,
	TEXTURE_ID_SCENE_FLOOR_13,
	TEXTURE_ID_SCENE_FLOOR_14,
	TEXTURE_ID_SCENE_FLOOR_15,
	TEXTURE_ID_SCENE_FLOOR_16,
	
	// Scene walls
	TEXTURE_ID_SCENE_WALL_0,
	TEXTURE_ID_SCENE_WALL_1,
	TEXTURE_ID_SCENE_WALL_2,
	TEXTURE_ID_SCENE_WALL_3,
	TEXTURE_ID_SCENE_WALL_4,
	TEXTURE_ID_SCENE_WALL_6,
	TEXTURE_ID_SCENE_WALL_7,
	
	// Static objects
	TEXTURE_ID_MEDIPACK,
	TEXTURE_ID_GOLDEN_MEDIPACK,
	TEXTURE_ID_AMMUNITION,
	TEXTURE_ID_ENEMY_SPAWNER,
	
	// Moving objects
	TEXTURE_ID_PLAYER_FACING_UP,
	TEXTURE_ID_PLAYER_FACING_DOWN,
	TEXTURE_ID_PLAYER_FACING_LEFT,
	TEXTURE_ID_PLAYER_FACING_RIGHT,
	TEXTURE_ID_SMALL_ENEMY_FACING_UP,
	TEXTURE_ID_SMALL_ENEMY_FACING_DOWN,
	TEXTURE_ID_SMALL_ENEMY_FACING_LEFT,
	TEXTURE_ID_SMALL_ENEMY_FACING_RIGHT,
	TEXTURE_ID_MEDIUM_ENEMY_FACING_UP,
	TEXTURE_ID_MEDIUM_ENEMY_FACING_DOWN,
	TEXTURE_ID_MEDIUM_ENEMY_FACING_LEFT,
	TEXTURE_ID_MEDIUM_ENEMY_FACING_RIGHT,
	TEXTURE_ID_BIG_ENEMY_FACING_UP,
	TEXTURE_ID_BIG_ENEMY_FACING_DOWN,
	TEXTURE_ID_BIG_ENEMY_FACING_LEFT,
	TEXTURE_ID_BIG_ENEMY_FACING_RIGHT,
	TEXTURE_ID_PLAYER_BULLET_FACING_UP,
	TEXTURE_ID_PLAYER_BULLET_FACING_DOWN,
	TEXTURE_ID_PLAYER_BULLET_FACING_LEFT,
	TEXTURE_ID_PLAYER_BULLET_FACING_RIGHT,
	TEXTURE_ID_SMALL_ENEMY_BULLET_FACING_UP,
	TEXTURE_ID_SMALL_ENEMY_BULLET_FACING_DOWN,
	TEXTURE_ID_SMALL_ENEMY_BULLET_FACING_LEFT,
	TEXTURE_ID_SMALL_ENEMY_BULLET_FACING_RIGHT,
	TEXTURE_ID_MEDIUM_ENEMY_BULLET_FACING_UP,
	TEXTURE_ID_MEDIUM_ENEMY_BULLET_FACING_DOWN,
	TEXTURE_ID_MEDIUM_ENEMY_BULLET_FACING_LEFT,
	TEXTURE_ID_MEDIUM_ENEMY_BULLET_FACING_RIGHT,
	TEXTURE_ID_BIG_ENEMY_BULLET_FACING_UP,
	TEXTURE_ID_BIG_ENEMY_BULLET_FACING_DOWN,
	TEXTURE_ID_BIG_ENEMY_BULLET_FACING_LEFT,
	TEXTURE_ID_BIG_ENEMY_BULLET_FACING_RIGHT,
	
	// Animated textures
	TEXTURE_ID_ENEMY_SPAWNER_EXPLOSION_0,
	TEXTURE_ID_ENEMY_SPAWNER_EXPLOSION_1,
	TEXTURE_ID_ENEMY_SPAWNER_EXPLOSION_2,
	TEXTURE_ID_ENEMY_SPAWNER_EXPLOSION_3,
	TEXTURE_ID_ENEMY_SPAWNER_EXPLOSION_4,
	TEXTURE_ID_ENEMY_SPAWNER_EXPLOSION_5,
	TEXTURE_ID_ENEMY_SPAWNER_EXPLOSION_6,
	TEXTURE_ID_ENEMY_SPAWNER_EXPLOSION_7,
	TEXTURE_ID_ENEMY_SPAWNER_EXPLOSION_8,
	TEXTURE_ID_ENEMY_SPAWNER_EXPLOSION_9,
	TEXTURE_ID_ENEMY_SPAWNER_EXPLOSION_10,
	TEXTURE_ID_ENEMY_SPAWNER_EXPLOSION_11,
	TEXTURE_ID_ENEMY_SPAWNER_EXPLOSION_12,
	TEXTURE_ID_ENEMY_SPAWNER_EXPLOSION_13,
	TEXTURE_ID_ENEMY_SPAWNER_EXPLOSION_14,
	TEXTURE_ID_ENEMY_SPAWNER_EXPLOSION_15,
	TEXTURE_ID_SMALL_ENEMY_EXPLOSION_0,
	TEXTURE_ID_SMALL_ENEMY_EXPLOSION_1,
	TEXTURE_ID_SMALL_ENEMY_EXPLOSION_2,
	TEXTURE_ID_SMALL_ENEMY_EXPLOSION_3,
	TEXTURE_ID_SMALL_ENEMY_EXPLOSION_4,
	TEXTURE_ID_SMALL_ENEMY_EXPLOSION_5,
	TEXTURE_ID_SMALL_ENEMY_EXPLOSION_6,
	TEXTURE_ID_SMALL_ENEMY_EXPLOSION_7,
	TEXTURE_ID_SMALL_ENEMY_EXPLOSION_8,
	TEXTURE_ID_SMALL_ENEMY_EXPLOSION_9,
	TEXTURE_ID_SMALL_ENEMY_EXPLOSION_10,
	TEXTURE_ID_SMALL_ENEMY_EXPLOSION_11,
	TEXTURE_ID_SMALL_ENEMY_EXPLOSION_12,
	TEXTURE_ID_SMALL_ENEMY_EXPLOSION_13,
	TEXTURE_ID_SMALL_ENEMY_EXPLOSION_14,
	TEXTURE_ID_SMALL_ENEMY_EXPLOSION_15,
	TEXTURE_ID_MEDIUM_ENEMY_EXPLOSION_0,
	TEXTURE_ID_MEDIUM_ENEMY_EXPLOSION_1,
	TEXTURE_ID_MEDIUM_ENEMY_EXPLOSION_2,
	TEXTURE_ID_MEDIUM_ENEMY_EXPLOSION_3,
	TEXTURE_ID_MEDIUM_ENEMY_EXPLOSION_4,
	TEXTURE_ID_MEDIUM_ENEMY_EXPLOSION_5,
	TEXTURE_ID_MEDIUM_ENEMY_EXPLOSION_6,
	TEXTURE_ID_MEDIUM_ENEMY_EXPLOSION_7,
	TEXTURE_ID_MEDIUM_ENEMY_EXPLOSION_8,
	TEXTURE_ID_MEDIUM_ENEMY_EXPLOSION_9,
	TEXTURE_ID_MEDIUM_ENEMY_EXPLOSION_10,
	TEXTURE_ID_MEDIUM_ENEMY_EXPLOSION_11,
	TEXTURE_ID_MEDIUM_ENEMY_EXPLOSION_12,
	TEXTURE_ID_MEDIUM_ENEMY_EXPLOSION_13,
	TEXTURE_ID_MEDIUM_ENEMY_EXPLOSION_14,
	TEXTURE_ID_MEDIUM_ENEMY_EXPLOSION_15,
	TEXTURE_ID_BIG_ENEMY_EXPLOSION_0,
	TEXTURE_ID_BIG_ENEMY_EXPLOSION_1,
	TEXTURE_ID_BIG_ENEMY_EXPLOSION_2,
	TEXTURE_ID_BIG_ENEMY_EXPLOSION_3,
	TEXTURE_ID_BIG_ENEMY_EXPLOSION_4,
	TEXTURE_ID_BIG_ENEMY_EXPLOSION_5,
	TEXTURE_ID_BIG_ENEMY_EXPLOSION_6,
	TEXTURE_ID_BIG_ENEMY_EXPLOSION_7,
	TEXTURE_ID_BIG_ENEMY_EXPLOSION_8,
	TEXTURE_ID_BIG_ENEMY_EXPLOSION_9,
	TEXTURE_ID_BIG_ENEMY_EXPLOSION_10,
	TEXTURE_ID_BIG_ENEMY_EXPLOSION_11,
	TEXTURE_ID_BIG_ENEMY_EXPLOSION_12,
	TEXTURE_ID_BIG_ENEMY_EXPLOSION_13,
	TEXTURE_ID_BIG_ENEMY_EXPLOSION_14,
	TEXTURE_ID_BIG_ENEMY_EXPLOSION_15,
	TEXTURE_ID_PLAYER_MUZZLE_FLASH_FACING_UP,
	TEXTURE_ID_PLAYER_MUZZLE_FLASH_FACING_DOWN,
	TEXTURE_ID_PLAYER_MUZZLE_FLASH_FACING_LEFT,
	TEXTURE_ID_PLAYER_MUZZLE_FLASH_FACING_RIGHT,
	TEXTURE_ID_SMALL_ENEMY_MUZZLE_FLASH_FACING_UP,
	TEXTURE_ID_SMALL_ENEMY_MUZZLE_FLASH_FACING_DOWN,
	TEXTURE_ID_SMALL_ENEMY_MUZZLE_FLASH_FACING_LEFT,
	TEXTURE_ID_SMALL_ENEMY_MUZZLE_FLASH_FACING_RIGHT,
	TEXTURE_ID_MEDIUM_ENEMY_MUZZLE_FLASH_FACING_UP,
	TEXTURE_ID_MEDIUM_ENEMY_MUZZLE_FLASH_FACING_DOWN,
	TEXTURE_ID_MEDIUM_ENEMY_MUZZLE_FLASH_FACING_LEFT,
	TEXTURE_ID_MEDIUM_ENEMY_MUZZLE_FLASH_FACING_RIGHT,
	TEXTURE_ID_BIG_ENEMY_MUZZLE_FLASH_FACING_UP,
	TEXTURE_ID_BIG_ENEMY_MUZZLE_FLASH_FACING_DOWN,
	TEXTURE_ID_BIG_ENEMY_MUZZLE_FLASH_FACING_LEFT,
	TEXTURE_ID_BIG_ENEMY_MUZZLE_FLASH_FACING_RIGHT,
	TEXTURE_ID_MEDIPACK_TAKEN_0,
	TEXTURE_ID_MEDIPACK_TAKEN_1,
	TEXTURE_ID_MEDIPACK_TAKEN_2,
	TEXTURE_ID_MEDIPACK_TAKEN_3,
	TEXTURE_ID_MEDIPACK_TAKEN_4,
	TEXTURE_ID_MEDIPACK_TAKEN_5,
	TEXTURE_ID_MEDIPACK_TAKEN_6,
	TEXTURE_ID_AMMUNITION_TAKEN_0,
	TEXTURE_ID_AMMUNITION_TAKEN_1,
	TEXTURE_ID_AMMUNITION_TAKEN_2,
	
	// Overlays
	TEXTURE_ID_PLAYER_HIT_OVERLAY,
	
	// Graphic user interface
	TEXTURE_ID_GRAPHIC_USER_INTERFACE_BACKGROUND,
	
	TEXTURE_IDS_COUNT
} TextureId;

//-------------------------------------------------------------------------------------------------
// Functions
//-------------------------------------------------------------------------------------------------
/** Load all game textures.
 * @return 0 if all textures were successfully initialized,
 * @return -1 if an error occurred.
 */
int initialize();

/** Free all allocated resources. */
void uninitialize();

/** Retrieve a texture.
 * @param id The texture identifier.
 * @return The texture or NULL if the provided ID is bad.
 */
Texture *getTextureFromId(TextureId id);

}

#endif