name: Release builds
on: [push]

jobs:
  linux_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies installation
        run: |
          sudo apt update
          sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
      - name: Linux release build
        run: make linux_release

  macos_build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: macOS release build
        run: make macos_release

  windows_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies installation
        run: |
          sudo apt update
          sudo apt install -y mingw-w64
      - name: Windows release build
        run: make windows_release
