name: Release builds
on: [push]

jobs:
  linux_build:
    runs-on: ubuntu-latest
    name: Linux
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies installation
        run: |
          sudo apt update
          sudo apt install -y libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
      - name: Linux release build
        run: make linux_release
      - name: Release (if a tag was specified)
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/../Strage_Version_*_Linux.tar.xz
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}

  macos_build:
    runs-on: macos-latest
    name: macOS
    steps:
      - uses: actions/checkout@v4
      - name: macOS release build
        run: make macos_release
      - name: Release (if a tag was specified)
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/../Strage_Version_*_MacOS.zip
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}

  windows_build:
    runs-on: ubuntu-latest
    name: Windows
    steps:
      - uses: actions/checkout@v4
      - name: Dependencies installation
        run: |
          sudo apt update
          sudo apt install -y mingw-w64
      - name: Windows release build
        run: make windows_release
      - name: Release (if a tag was specified)
        if: startsWith(github.ref, 'refs/tags')
        uses: softprops/action-gh-release@v1
        with:
          files: ${{ github.workspace }}/../Strage_Version_*_Windows.zip
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref_name }}
